name: Test

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      uses: actions/checkout@v2
    - run: ls -la
    - run: cat README.md
   
        
      
