name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone project
      run: git clone https://github.com/johnpapa/node-hello.git

    - name: Cache project
      uses: actions/cache@v2
      with:
        path: package-lock.json
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
