name: Caching

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cache project
      uses: actions/cache@v2
      with:
        path:  ~/.npm
        key: Linux-node-20392547f5cec4079f98ba9598bdcb921b7cc3f7cf77718f50b7c78ec0844fb5
