name: Test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    steps:
    - name: Cache project
      uses: actions/checkout@v2
    - run: ls -la
    - run: cat README.md
   
        
      
