name: Caching

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -X GET 'https://artifactcache.actions.githubusercontent.com/JkiWAICOGKccZIzjB7hSQ4JEvqd2QjQOSrZ3BbO0tXZbopoAhK/_apis/artifactcache/cache?keys=Linux-node-20392547f5cec4079f98ba9598bdcb921b7cc3f7cf77718f50b7c78ec0844fb5&version=c242501c19ada3dcced7a83b074ccb8e79f816602d4125493924624b38591de2'  -H 'Content-Type: application/json;api-version=6.0-preview.1' -H 'User-Agent: actions/cache' -H 'Authorization: Bearer ASS3YZIMQS7TDQSBW7O3PTTA73WVY'
    - run: ls -la
    

